max_container: 10
actions:
  - name: image
    image: action_image
    qos_time: 0.1
    qos_requirement: 0.95
  - name: network
    image: action_network
    qos_time: 0.1
    qos_requirement: 0.95
  - name: video
    image: action_video
    qos_time: 0.1
    qos_requirement: 0.95
  - name: float_operation
    image: action_float_operation
    qos_time: 0.1
    qos_requirement: 0.95
  - name: disk
    image: action_disk
    qos_time: 0.1
    qos_requirement: 0.95
  - name: linpack
    image: action_linpack
    qos_time: 0.1
    qos_requirement: 0.95
  - name: matmul
    image: action_matmul
    qos_time: 0.1
    qos_requirement: 0.95
  - name: map_reduce
    image: action_map_reduce
    qos_time: 0.1
    qos_requirement: 0.95
  - name: couchdb_test
    image: action_couchdb_test
    qos_time: 0.1
    qos_requirement: 0.95
  - name: markdown2html
    image: action_markdown2html
    qos_time: 0.1
    qos_requirement: 0.95
  - name: k-means
    image: action_k-means
    qos_time: 0.1
    qos_requirement: 0.95
