FROM action_fp_conversion
RUN pip3 --no-cache-dir install aws_requests_auth elasticsearch certifi chardet idna requests urllib3 tox moto wheel freezegun sure dynamodb-encryption-sdk cryptography pyutu