actions:
- image: action_cs_bot
  name: cs_bot
  qos_requirement: 0.95
  qos_time: 1
- image: action_cer_lambda
  name: cer_lambda
  qos_requirement: 0.95
  qos_time: 1
- image: action_df_union
  name: df_union
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_users_sign_up
  name: ep_users_sign_up
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_products_table_update
  name: ep_products_table_update
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_orders_create_order
  name: ep_orders_create_order
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_products_validate
  name: ep_products_validate
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_delivery_on_package_created
  name: ep_delivery_on_package_created
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_payment_validate
  name: ep_payment_validate
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_warehouse_on_order_events
  name: ep_warehouse_on_order_events
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_warehouse_table_update
  name: ep_warehouse_table_update
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_payment_cancel_payment
  name: ep_payment_cancel_payment
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_delivery_table_requests
  name: ep_delivery_table_requests
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_payment_process_payment
  name: ep_payment_process_payment
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_orders_on_event
  name: ep_orders_on_event
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_orders_table_update
  name: ep_orders_table_update
  qos_requirement: 0.95
  qos_time: 1
- image: action_ep_payment_update_payment
  name: ep_payment_update_payment
  qos_requirement: 0.95
  qos_time: 1
- image: action_eo_athenarunner
  name: eo_athenarunner
  qos_requirement: 0.95
  qos_time: 1
- image: action_eo_gluerunner
  name: eo_gluerunner
  qos_requirement: 0.95
  qos_time: 1
- image: action_eo_ons3objectcreated
  name: eo_ons3objectcreated
  qos_requirement: 0.95
  qos_time: 1
- image: action_fmp_twitter_streaming
  name: fmp_twitter_streaming
  qos_requirement: 0.95
  qos_time: 1
- image: action_fmp_twitterddb
  name: fmp_twitterddb
  qos_requirement: 0.95
  qos_time: 1
- image: action_fmp_comparefaces
  name: fmp_comparefaces
  qos_requirement: 0.95
  qos_time: 1
- image: action_fp_notification
  name: fp_notification
  qos_requirement: 0.95
  qos_time: 1
- image: action_fp_conversion
  name: fp_conversion
  qos_requirement: 0.95
  qos_time: 1
- image: action_fp_sentiment
  name: fp_sentiment
  qos_requirement: 0.95
  qos_time: 1
- image: action_t_payment_method
  name: t_payment_method
  qos_requirement: 0.95
  qos_time: 1
- image: action_t_ddb_encrypt_item
  name: t_ddb_encrypt_item
  qos_requirement: 0.95
  qos_time: 1
- image: action_sc_add_to_cart
  name: sc_add_to_cart
  qos_requirement: 0.95
  qos_time: 1
- image: action_sc_update_cart
  name: sc_update_cart
  qos_requirement: 0.95
  qos_time: 1
- image: action_sc_list_cart
  name: sc_list_cart
  qos_requirement: 0.95
  qos_time: 1
- image: action_sc_migrate_cart
  name: sc_migrate_cart
  qos_requirement: 0.95
  qos_time: 1
- image: action_sc_checkout_cart
  name: sc_checkout_cart
  qos_requirement: 0.95
  qos_time: 1
- image: action_sc_delete_from_cart
  name: sc_delete_from_cart
  qos_requirement: 0.95
  qos_time: 1
- image: action_tcp_download_podcast
  name: tcp_download_podcast
  qos_requirement: 0.95
  qos_time: 1
- image: action_tcp_check_transcribe
  name: tcp_check_transcribe
  qos_requirement: 0.95
  qos_time: 1
- image: action_tcp_process_podcast_rss
  name: tcp_process_podcast_rss
  qos_requirement: 0.95
  qos_time: 1
- image: action_tcp_upload_to_elasticsearch
  name: tcp_upload_to_elasticsearch
  qos_requirement: 0.95
  qos_time: 1
max_container: 10
